### ISSUE TITLE
gmx.com - better should be NOT in the list

### ISSUE THREAD

**Issue by knubew** [hassanazimi/List-of-Disposable-Email-Addresses#1]
Hi,

I think the domain "gmx.com" better should be NOT in the list. GMX (http://www.gmx.net/ or http://www.gmx.de/) is a big German Provider (1&1 Mail & Media GmbH) with a very good reputation, who has millions of customers in Germany. They offer Freemail, as well as different payed mail services. I also have a payed GMX Mailaccount with a "gmx.com" mail address.

**Comment by azimidev** [comment]
Thank you that has been fixed now.
