### ISSUE TITLE
"mail.ru" is not a disposable email address

### ISSUE THREAD

**Issue by knubew** [hassanazimi/List-of-Disposable-Email-Addresses#2]
Hi,

I think "mail.ru" is not a disposable email address. We have a few hundred customers who have "mail.ru" email addresses. Just have a look under [https://en.wikipedia.org/wiki/Mail.Ru](https://en.wikipedia.org/wiki/Mail.Ru).

**Comment by azimidev** [comment]
That is removed thank you.
